apiVersion: apps/v1 #NESTE ARWUIVO TEMOS UM EXEMPLO DE DEPLOYMENT COM SERVICE
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: meupod
  template:
    metadata: 
      labels:
        app: meupod 
    spec:
        containers:
          - name: site
            image: fabricioveronez/web-page:green
            ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  selector:
    app: meupod #aqui cria-se um link com o pod existente
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000 #quando se quer forçar uma porta no serviço, não pegando mais aleatorio
  type: NodePort


