apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:
  containers:
    - name: site
      image: fabricioveronez/web-page:blue
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: meu2pod
  labels:
    app: segundo

spec:
  containers:
    - name: site
      image: fabricioveronez/web-page:blue
      ports:
      - containerPort: 80